### ISSUE TITLE
Running `./gradlew run` results in failure

### ISSUE THREAD

**Issue by Gohla** [metaborg/spoofax-intellij#4]
Running `./gradlew run` results in failure instead of running IntelliJ with Spoofax.

I tried to do this:

`./gradlew run`

I expected this to happen: 

IntelliJ to start up with the Spoofax plugin loaded.

Instead, this happened:

Running this command results in an injection error, see the log:

```
spoofax-intellij [master]±% ./gradlew run
Downloading https://services.gradle.org/distributions/gradle-3.2.1-bin.zip
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /Users/gohla/.gradle/wrapper/dists/gradle-3.2.1-bin/erlz51pt56t1o6vc7t39cikug/gradle-3.2.1-bin.zip to /Users/gohla/.gradle/wrapper/dists/gradle-3.2.1-bin/erlz51pt56t1o6vc7t39cikug
Set executable permissions for: /Users/gohla/.gradle/wrapper/dists/gradle-3.2.1-bin/erlz51pt56t1o6vc7t39cikug/gradle-3.2.1/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
:run
plugin.xml with 'idea-plugin' root is not found. IntelliJ specific tasks will be unavailable for :org.metaborg.jps.
plugin.xml with 'idea-plugin' root is not found. IntelliJ specific tasks will be unavailable for :org.metaborg.spoofax-common.
:org.metaborg.intellij:org.metaborg.spoofax-deps:compileJava UP-TO-DATE
:org.metaborg.intellij:org.metaborg.spoofax-deps:processResources UP-TO-DATE
:org.metaborg.intellij:org.metaborg.spoofax-deps:classes UP-TO-DATE
:org.metaborg.intellij:org.metaborg.spoofax-deps:shadowJar UP-TO-DATE
:org.metaborg.intellij:org.metaborg.spoofax-common:compileJava UP-TO-DATE
:org.metaborg.intellij:org.metaborg.spoofax-common:processResources UP-TO-DATE
:org.metaborg.intellij:org.metaborg.spoofax-common:classes
:org.metaborg.intellij:org.metaborg.spoofax-common:jar UP-TO-DATE
:org.metaborg.intellij:org.metaborg.jps:compileJava
/Users/gohla/spoofax/master/repo/spoofax-releng/spoofax-intellij/org.metaborg.jps/src/main/java/org/metaborg/intellij/jps/PriorityURLClassLoader.java:22: warning: CompoundEnumeration is internal proprietary API and may be removed in a future release
import sun.misc.CompoundEnumeration;
               ^
/Users/gohla/spoofax/master/repo/spoofax-releng/spoofax-intellij/org.metaborg.jps/src/main/java/org/metaborg/intellij/jps/PriorityURLClassLoader.java:262: warning: CompoundEnumeration is internal proprietary API and may be removed in a future release
        return new CompoundEnumeration<>(resources);
                   ^
2 warnings
:org.metaborg.intellij:org.metaborg.jps:processResources UP-TO-DATE
:org.metaborg.intellij:org.metaborg.jps:classes
:org.metaborg.intellij:org.metaborg.jps:jar UP-TO-DATE
:org.metaborg.intellij:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:org.metaborg.intellij:copyLanguageDependencies UP-TO-DATE
:org.metaborg.intellij:copyLanguageBaselineDependencies UP-TO-DATE
:org.metaborg.intellij:processResources UP-TO-DATE
:org.metaborg.intellij:classes
:org.metaborg.intellij:prepareSandbox UP-TO-DATE
:org.metaborg.intellij:runIdea
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0
/Users/gohla/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2016.3/fdb42db1447ad402d0476e6e0c5933ab5d56c992/ideaIC-2016.3/bin/mac/idea.properties: 'java.endorsed.dirs' already defined
/Users/gohla/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2016.3/fdb42db1447ad402d0476e6e0c5933ab5d56c992/ideaIC-2016.3/bin/mac/idea.properties: 'idea.smooth.progress' already defined
/Users/gohla/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2016.3/fdb42db1447ad402d0476e6e0c5933ab5d56c992/ideaIC-2016.3/bin/mac/idea.properties: 'apple.laf.useScreenMenuBar' already defined
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [file:/Users/gohla/spoofax/master/repo/spoofax-releng/spoofax-intellij/org.metaborg.intellij/build/idea-sandbox/plugins/org.metaborg.intellij/classes/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/gohla/spoofax/master/repo/spoofax-releng/spoofax-intellij/org.metaborg.intellij/build/idea-sandbox/plugins/org.metaborg.intellij/lib/org.metaborg.intellij-common-2.1.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/gohla/spoofax/master/repo/spoofax-releng/spoofax-intellij/org.metaborg.intellij/build/idea-sandbox/plugins/org.metaborg.intellij/lib/org.metaborg.spoofax-common-2.1.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/gohla/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2016.3/fdb42db1447ad402d0476e6e0c5933ab5d56c992/ideaIC-2016.3/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.IntelliJLoggerFactory]

Plugin Error: Plugin 'org.metaborg.intellij' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.RuntimeException: org.metaborg.core.MetaborgException: Could not create injector because of dependency injection errors
        at org.metaborg.intellij.idea.SpoofaxIdeaPlugin.<init>(SpoofaxIdeaPlugin.java:97)
        at org.metaborg.intellij.idea.SpoofaxIdeaPlugin.<init>(SpoofaxIdeaPlugin.java:38)
        at org.metaborg.intellij.idea.SpoofaxIdeaPlugin$1.initialize(SpoofaxIdeaPlugin.java:46)
        at org.metaborg.intellij.idea.SpoofaxIdeaPlugin$1.initialize(SpoofaxIdeaPlugin.java:43)
        at org.apache.commons.lang3.concurrent.LazyInitializer.get(LazyInitializer.java:103)
        at org.metaborg.intellij.idea.SpoofaxIdeaPlugin.plugin(SpoofaxIdeaPlugin.java:80)
        at org.metaborg.intellij.idea.SpoofaxIdeaPlugin.spoofaxMeta(SpoofaxIdeaPlugin.java:71)
        at org.metaborg.intellij.idea.SpoofaxIdeaPlugin.injector(SpoofaxIdeaPlugin.java:56)
        at org.metaborg.intellij.idea.IdeaApplicationComponent.<init>(IdeaApplicationComponent.java:50)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
        at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:58)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:478)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$8(ApplicationImpl.java:441)
        at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
        at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:448)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:400)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:386)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
        at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:47)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.metaborg.core.MetaborgException: Could not create injector because of dependency injection errors
        at org.metaborg.core.plugin.InjectorFactory.create(InjectorFactory.java:36)
        at org.metaborg.core.MetaBorg.<init>(MetaBorg.java:84)
        at org.metaborg.core.MetaBorgGeneric.<init>(MetaBorgGeneric.java:108)
        at org.metaborg.spoofax.core.Spoofax.<init>(Spoofax.java:49)
        at org.metaborg.intellij.idea.SpoofaxIdeaPlugin.<init>(SpoofaxIdeaPlugin.java:94)
        ... 46 more
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.util.Set<org.metaborg.intellij.discovery.ILanguageSource> annotated with @org.metaborg.intellij.idea.projects.Compound() was bound.
  while locating java.util.Set<org.metaborg.intellij.discovery.ILanguageSource> annotated with @org.metaborg.intellij.idea.projects.Compound()
    for parameter 0 at org.metaborg.intellij.discovery.MultiLanguageSource.<init>(MultiLanguageSource.java:46)
  at org.metaborg.intellij.idea.IdeaSpoofaxModule.bindLanguageSources(IdeaSpoofaxModule.java:160)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at org.metaborg.core.plugin.InjectorFactory.create(InjectorFactory.java:34)
        ... 50 more

:org.metaborg.intellij:runIdea FAILED
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runIdea'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java'' finished with non-zero exit value 8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 50.048 secs
```

---

Latest master at this time.

**Comment by Virtlink** [comment]
I've seen this error many times, and I still don't know what triggers it. I can't reproduce this locally yet. :S

**Comment by Gohla** [comment]
One thing I see is that the error message notes the `org.metaborg.intellij.idea.projects.Compound` annotation interface, whereas the [Compound annotation interface](https://github.com/metaborg/spoofax-intellij/blob/master/org.metaborg.spoofax-common/src/main/java/org/metaborg/intellij/Compound.java) is in the `org.metaborg.intellij` package. Is that intentional?

Other possible causes:

* File/directory names case-sensitive on git, causing problems on case-insensitive file systems? Changing case also causes problems. I'm running macOS with a case-insensitive file system.
* Different JVM/JDK versions? I'm running `jdk1.8.0_112`.
* Different versions of other things: Gradle, IntelliJ, etc.?
* Different operating systems.

**Comment by Virtlink** [comment]
Do you happen to have a file `Compound.java` in some other location than `org.metaborg.spoofax-common/src/main/java/org/metaborg/intellij/`? Maybe a stray file that should not be there?

The package for the `Compound` attribute is [correct in my source code](https://github.com/metaborg/spoofax-intellij/blob/master/org.metaborg.spoofax-common/src/main/java/org/metaborg/intellij/Compound.java#L19), but due to the [global import in `IdeaSpoofaxModule`](https://github.com/metaborg/spoofax-intellij/blob/master/org.metaborg.intellij/src/main/java/org/metaborg/intellij/idea/IdeaSpoofaxModule.java#L41) it might pick up a stray file that I don't have.

**Comment by Gohla** [comment]
Nope:

```
spoofax-releng [master]±% find . -name 'Compound.java'
./spoofax-intellij/org.metaborg.spoofax-common/src/main/java/org/metaborg/intellij/Compound.java
```

**Comment by Gohla** [comment]
In commit https://github.com/metaborg/spoofax-intellij/tree/8a32782bdb9504a521801b85805ab55b5d8c0ccf/org.metaborg.intellij/src/main/java/org/metaborg/intellij/idea/projects, the Compound class was still in that directory, but the following change moved it: https://github.com/metaborg/spoofax-intellij/commit/d65b4bd82edf3fc56976989c6e206022500393a1#diff-6008d48e24435e5c70480b953781afec

Maybe there's still a dependency on this older version?

**Comment by Virtlink** [comment]
Can you try `./gradlew clean run`?

**Comment by Gohla** [comment]
That seems to work, IntelliJ now starts! So the dependency tracking is off somehow?

**Comment by Virtlink** [comment]
Great. Yes apparently. I suspected that since I saw you have many `UP-TO-DATE` messages in your build log.

In this case I believe the `shadowJar` task didn't track dependencies properly.
